# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sslQrqBTD8swRbIqXcY8gPVPf3I0hlBP
"""

from fastapi import FastAPI, Request
import requests
import os

app = FastAPI()

SHOPIFY_ADMIN_TOKEN = os.getenv("SHOPIFY_ADMIN_TOKEN")
SHOPIFY_DOMAIN = "fullstopbeest.myshopify.com"

# Mapping of main SKUs to freebie SKUs
FREEBIE_MAP = {
    "B-BP-SFI-12PK-V2-SHP": [
        "FREE-B-BP-PPE-V1",
        "FREE-B-BP-SPC-2PK-V1"
    ],
    "B-BP-SFI-6PK-V3": [
        "FREE-B-BP-APPLICAT-XX-V1"
    ]
}

@app.post("/webhook/orders/create")
async def order_created(request: Request):
    payload = await request.json()
    order_id = payload.get("id")
    line_items = payload.get("line_items", [])

    print(f"🔔 New Order #{order_id} received")

    # Collect all SKUs in the order
    order_skus = [item.get("sku") for item in line_items]

    # Identify main SKUs in the order
    freebies_to_add = []
    for sku in order_skus:
        freebies_to_add.extend(FREEBIE_MAP.get(sku, []))

    if not freebies_to_add:
        print("✅ No freebies required for this order.")
        return {"status": "no_freebies"}

    print(f"🎁 Adding freebies: {freebies_to_add}")

    # Get variant IDs for freebies using Admin API
    variant_ids = []
    for freebie_sku in freebies_to_add:
        resp = requests.get(
            f"https://{SHOPIFY_DOMAIN}/admin/api/2025-01/variants.json?sku={freebie_sku}",
            headers={"X-Shopify-Access-Token": SHOPIFY_ADMIN_TOKEN}
        )
        data = resp.json()
        if data.get("variants"):
            variant_ids.append(data["variants"][0]["id"])

    # Add freebies to the order as new line items (if Draft or editable)
    for variant_id in variant_ids:
        add_line_item(order_id, variant_id)

    return {"status": "freebies_added", "freebie_count": len(variant_ids)}


def add_line_item(order_id, variant_id, qty=1):
    url = f"https://{SHOPIFY_DOMAIN}/admin/api/2025-01/orders/{order_id}/metafields.json"
    # Shopify doesn’t allow modifying fulfilled orders directly;
    # you can either tag the order or create a fulfillment/draft order.
    # For tagging/logging purpose:
    requests.post(
        url,
        headers={"X-Shopify-Access-Token": SHOPIFY_ADMIN_TOKEN},
        json={
            "metafield": {
                "namespace": "freebie",
                "key": f"variant_{variant_id}",
                "value": "added",
                "type": "single_line_text_field"
            }
        }
    )
    print(f"📝 Logged freebie {variant_id} to order {order_id}")